[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts-ccip/src/v0.8/ccip/=lib/chainlink-ccip/chains/evm/contracts/",
    "@chainlink/contracts-ccip/src/v0.8/vendor/openzeppelin-solidity/v5.0.2/=lib/openzeppelin-contracts/contracts/"
]

via_ir = true
optimizer = true
optimizer_runs = 200

# Dependencies - 自動インストール用
[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.8.2" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.0.2" }
chainlink-ccip = { git = "https://github.com/smartcontractkit/chainlink-ccip", tag = "contracts-ccip-v1.6.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
