[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts-ccip/src/v0.8/ccip/=lib/chainlink-ccip/chains/evm/contracts/",
    "@openzeppelin=lib/openzeppelin-contracts/contracts/"
]

via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
